name: segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - ipykernel
  - ipython
  - jupyterlab
  - notebook=7.0.6
  - numpy=1.26.3
  - pandas=2.1.4
  - plotly=5.18.0
  - scikit-learn=1.3.0
  - seaborn=0.13.2
  - streamlit=1.30.0
