name: segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - ipykernel
  - ipython
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - plotly
  - scikit-learn
  - seaborn
  - streamlit
